-- Migration: Ajouter produits fruits et légumes (avec vérification d'existence)
DO $$
DECLARE
  fruits_category_id UUID;
  legumes_category_id UUID;
BEGIN
  -- Récupérer les IDs des catégories
  SELECT id INTO fruits_category_id FROM categories WHERE name ILIKE '%fruit%' LIMIT 1;
  SELECT id INTO legumes_category_id FROM categories WHERE name ILIKE '%légume%' OR name ILIKE '%legume%' LIMIT 1;
  
  -- Si catégories n'existent pas, les créer
  IF fruits_category_id IS NULL THEN
    INSERT INTO categories (name, color, icon) VALUES ('Fruits', '#FF6B6B', 'Apple')
    RETURNING id INTO fruits_category_id;
  END IF;
  
  IF legumes_category_id IS NULL THEN
    INSERT INTO categories (name, color, icon) VALUES ('Légumes', '#4ECDC4', 'Carrot')
    RETURNING id INTO legumes_category_id;
  END IF;

  -- Insérer les produits qui n'existent pas encore (basé sur le barcode)
  -- FRUITS
  INSERT INTO products (barcode, name, price, type, unit, category_id, vat_rate, stock, is_active)
  SELECT v.barcode, v.name, v.price, v.type::product_type, v.unit, fruits_category_id, 6, 0, true
  FROM (VALUES
    ('301', 'Abricot Petit', 2.99, 'weight', 'kg'),
    ('302', 'Ananas Jaunes Côte d''Ivoire', 1.29, 'unit', 'pièce'),
    ('303', 'Avocats Haas', 0, 'unit', 'pièce'),
    ('304', 'Banane', 0, 'weight', 'kg'),
    ('305', 'Banane Chiquita', 0, 'weight', 'kg'),
    ('306', 'Carambole', 0, 'unit', 'pièce'),
    ('307', 'Cerises', 9.99, 'weight', 'kg'),
    ('308', 'Châtaigne', 1.99, 'weight', 'kg'),
    ('309', 'Cherimole', 1.29, 'unit', 'pièce'),
    ('310', 'Citron Non Traité', 0, 'weight', 'kg'),
    ('311', 'Citron Jaune', 2.99, 'weight', 'kg'),
    ('312', 'Citron Vert', 0.95, 'unit', 'pièce'),
    ('313', 'Clémentine', 2.99, 'weight', 'kg'),
    ('314', 'Clémentine Feuilles', 0, 'weight', 'kg'),
    ('315', 'Clémentine Nadorcott', 0, 'weight', 'kg'),
    ('316', 'Figue Barbarie', 0, 'unit', 'pièce'),
    ('317', 'Figue Fraîche', 0, 'unit', 'pièce'),
    ('318', 'Fraise Pays Petite 500g', 3.95, 'unit', 'barquette'),
    ('319', 'Fraise Pays Extra 500g', 4.99, 'unit', 'barquette'),
    ('320', 'Fraise Wépion', 0, 'unit', 'barquette'),
    ('321', 'Framboise 125g', 2.99, 'unit', 'barquette'),
    ('322', 'Kiwi Jaune', 3.99, 'unit', 'pièce'),
    ('323', 'Grenade Sucrée', 2.99, 'weight', 'kg'),
    ('324', 'Grenade Sur', 3.99, 'weight', 'kg'),
    ('325', 'Groseille Rouge 125g', 2.29, 'unit', 'barquette'),
    ('326', 'Kaki Classique Ravier 3pc', 3.99, 'unit', 'ravier'),
    ('327', 'Kaki Pomme', 2.99, 'weight', 'kg'),
    ('328', 'Kiwi Vert', 2.50, 'unit', 'pièce'),
    ('329', 'Kiwi Vert Ravier 1kg', 3.99, 'unit', 'ravier'),
    ('330', 'Litchi', 12.95, 'weight', 'kg'),
    ('331', 'Mandarine', 2.99, 'weight', 'kg'),
    ('333', 'Mangue', 1.99, 'unit', 'pièce'),
    ('335', 'Melon Charentais Extra', 2.99, 'unit', 'pièce'),
    ('336', 'Melon Charentais', 2.99, 'unit', 'pièce'),
    ('337', 'Melon Jaune', 1.89, 'weight', 'kg'),
    ('338', 'Melon Turc', 1.29, 'weight', 'kg'),
    ('339', 'Melon Vert', 1.89, 'weight', 'kg'),
    ('340', 'Melon Galia', 1.99, 'unit', 'pièce'),
    ('341', 'Mineolas', 0, 'weight', 'kg'),
    ('342', 'Nectarine Blanche', 3.99, 'weight', 'kg'),
    ('343', 'Nectarine Jaune', 3.99, 'weight', 'kg'),
    ('345', 'Nèfles GG', 6.99, 'weight', 'kg'),
    ('347', 'Noisette Fraîche', 6.99, 'weight', 'kg'),
    ('348', 'Noix de Coco', 1.49, 'unit', 'pièce'),
    ('349', 'Noix Fraîche', 4.99, 'weight', 'kg'),
    ('351', 'Orange Jus', 1.29, 'weight', 'kg'),
    ('352', 'Orange Montagne', 0, 'weight', 'kg'),
    ('353', 'Orange Non Traité', 2.99, 'weight', 'kg'),
    ('354', 'Orange Papillon', 0, 'weight', 'kg'),
    ('355', 'Orange Sanguinelli', 0, 'weight', 'kg'),
    ('356', 'Pamplemousse Blanc', 0.99, 'weight', 'kg'),
    ('357', 'Pamplemousse Rouge', 0, 'weight', 'kg'),
    ('358', 'Papaya', 0, 'unit', 'pièce'),
    ('359', 'Pastèque', 1.29, 'weight', 'kg'),
    ('360', 'Pastèque Coupée', 0, 'weight', 'kg'),
    ('361', 'Pastèque Grecque', 0.99, 'weight', 'kg'),
    ('362', 'Pastèque Noire', 0.99, 'weight', 'kg'),
    ('363', 'Pastèque Sans Pépin', 0.99, 'weight', 'kg'),
    ('364', 'Pêche Blanche', 3.99, 'weight', 'kg'),
    ('365', 'Pêche Jaune', 3.95, 'weight', 'kg'),
    ('366', 'Pêche Plate', 3.95, 'weight', 'kg'),
    ('367', 'Pêche Promo', 1.29, 'weight', 'kg'),
    ('368', 'Physalis Colombie', 0, 'unit', 'pièce'),
    ('369', 'Pitaya', 0, 'unit', 'pièce'),
    ('370', 'Poire Coing', 3.99, 'weight', 'kg'),
    ('371', 'Poire Conférence', 0, 'weight', 'kg'),
    ('372', 'Poire Doyenne', 2.89, 'weight', 'kg'),
    ('373', 'Poire Durandeau', 0, 'weight', 'kg'),
    ('374', 'Poire Guyaut', 2.99, 'weight', 'kg'),
    ('375', 'Poire Nashi', 2.99, 'weight', 'kg'),
    ('376', 'Poire Qtée Rouge', 2.99, 'weight', 'kg'),
    ('377', 'Poire Turc Santa', 4.95, 'weight', 'kg'),
    ('378', 'Pomelo Blanc', 0.99, 'unit', 'pièce'),
    ('379', 'Pomme Boscop', 0, 'weight', 'kg'),
    ('380', 'Pomme Fudji Rose', 0, 'weight', 'kg'),
    ('381', 'Pomme Golden Pays', 1.99, 'weight', 'kg'),
    ('382', 'Pomme Golden Rosée', 2.99, 'weight', 'kg'),
    ('383', 'Pomme Granny', 2.99, 'weight', 'kg'),
    ('384', 'Pomme Jonagold', 2.39, 'weight', 'kg'),
    ('385', 'Pomme Mini Jonagold', 0, 'weight', 'kg'),
    ('386', 'Pomme Pink Lady', 2.99, 'weight', 'kg'),
    ('387', 'Pomme Royal Gala', 2.99, 'weight', 'kg'),
    ('388', 'Pomme Starking', 2.99, 'weight', 'kg'),
    ('389', 'Mini Banane', 0, 'weight', 'kg'),
    ('390', 'Prune Blanche', 3.95, 'weight', 'kg'),
    ('391', 'Prune Président', 2.99, 'weight', 'kg'),
    ('392', 'Prune Reine Claude', 4.99, 'weight', 'kg'),
    ('393', 'Prune Rouge', 2.99, 'weight', 'kg'),
    ('394', 'Prune Stanley', 1.99, 'weight', 'kg'),
    ('395', 'Raisin Blanc', 2.99, 'weight', 'kg'),
    ('396', 'Raisin Blanc S.Pépin', 0, 'weight', 'kg'),
    ('397', 'Citron Filet 500g', 1.49, 'unit', 'filet'),
    ('398', 'Mûres 125g', 2.29, 'unit', 'barquette'),
    ('399', 'Myrtilles 125g', 2.29, 'unit', 'barquette'),
    ('400', 'Banane Plantin', 0, 'weight', 'kg'),
    ('401', 'Raisin Noir', 4.99, 'weight', 'kg'),
    ('402', 'Raisin Noir Muscat', 6.99, 'weight', 'kg'),
    ('403', 'Raisin Rose', 3.99, 'weight', 'kg'),
    ('404', 'Ramboutan', 0, 'weight', 'kg'),
    ('405', 'Sharon', 2.99, 'weight', 'kg'),
    ('417', 'Kelek', 4.99, 'weight', 'kg'),
    ('493', 'Nectarine Promo', 1.29, 'weight', 'kg')
  ) AS v(barcode, name, price, type, unit)
  WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.barcode = v.barcode);

  -- LÉGUMES
  INSERT INTO products (barcode, name, price, type, unit, category_id, vat_rate, stock, is_active)
  SELECT v.barcode, v.name, v.price, v.type::product_type, v.unit, legumes_category_id, 6, 0, true
  FROM (VALUES
    ('10', 'Artichaut Blanc', 0, 'unit', 'pièce'),
    ('13', 'Artichaut Violet', 0, 'unit', 'pièce'),
    ('14', 'Artichaut Botte', 3.99, 'unit', 'botte'),
    ('15', 'Asperge Blanc 500g', 0, 'unit', 'botte'),
    ('16', 'Asperges Verte 500g', 1.99, 'unit', 'botte'),
    ('17', 'Aubergine Long', 3.99, 'weight', 'kg'),
    ('18', 'Aubergine', 2.99, 'weight', 'kg'),
    ('19', 'Aubergine Violet', 3.99, 'weight', 'kg'),
    ('20', 'Betterave Précuite', 1.99, 'unit', 'sachet'),
    ('22', 'Bette', 0, 'weight', 'kg'),
    ('23', 'Betterave Rouge', 1.99, 'weight', 'kg'),
    ('26', 'Carotte Ravier 1kg', 1.79, 'unit', 'ravier'),
    ('27', 'Brocoli', 1.79, 'unit', 'pièce'),
    ('28', 'Cardon', 1.99, 'weight', 'kg'),
    ('30', 'Carotte Botte', 0.99, 'unit', 'botte'),
    ('31', 'Carotte Extra', 0, 'weight', 'kg'),
    ('32', 'Carotte 2kg', 1.99, 'unit', 'sachet'),
    ('33', 'Catalogne', 2.99, 'weight', 'kg'),
    ('35', 'Céleri Rave', 0.99, 'unit', 'pièce'),
    ('36', 'Céleri Vert', 0, 'unit', 'pièce'),
    ('38', 'Champignon Pleurotte', 6.99, 'weight', 'kg'),
    ('39', 'Champignon 500g', 2.00, 'unit', 'barquette'),
    ('40', 'Chicon Pays', 0, 'weight', 'kg'),
    ('41', 'Choux Blanc Farcir', 2.39, 'weight', 'kg'),
    ('42', 'Choux Chinois', 0, 'unit', 'pièce'),
    ('43', 'Choux de Bruxelles', 1.99, 'weight', 'kg'),
    ('44', 'Choux Fleur', 0.99, 'unit', 'pièce'),
    ('45', 'Choux Romanesco', 0, 'unit', 'pièce'),
    ('46', 'Choux Rouge', 0.49, 'unit', 'pièce'),
    ('47', 'Choux Rave Blanc', 0.99, 'unit', 'pièce'),
    ('48', 'Choux Vert', 0.69, 'unit', 'pièce'),
    ('49', 'Cimata', 2.99, 'weight', 'kg'),
    ('50', 'Concombre Citir', 0, 'weight', 'kg'),
    ('51', 'Mini Concombre', 0, 'weight', 'kg'),
    ('52', 'Concombre', 0.99, 'weight', 'kg'),
    ('53', 'Cornichon', 0.79, 'unit', 'pièce'),
    ('54', 'Courgette Vert', 0, 'weight', 'kg'),
    ('55', 'Courgette Ronde', 0, 'weight', 'kg'),
    ('56', 'Courgette Blanc', 0, 'weight', 'kg'),
    ('57', 'Épinard Botte', 0, 'unit', 'botte'),
    ('58', 'Épinard Vrac', 0, 'weight', 'kg'),
    ('59', 'Épinard 300g', 0, 'unit', 'sachet'),
    ('60', 'Fenouil', 2.99, 'weight', 'kg'),
    ('61', 'Chêne Rouge', 0, 'unit', 'pièce'),
    ('62', 'Chêne Verte', 0, 'unit', 'pièce'),
    ('63', 'Frisée Blanche', 0, 'unit', 'pièce'),
    ('64', 'Frisée Rouge', 0.69, 'unit', 'pièce'),
    ('65', 'Frisée Verte', 0, 'unit', 'pièce'),
    ('66', 'Fève', 0, 'weight', 'kg'),
    ('67', 'Gingembre', 5.99, 'weight', 'kg'),
    ('68', 'Haricot Beurre', 0, 'weight', 'kg'),
    ('69', 'Haricot Vert', 3.95, 'weight', 'kg'),
    ('73', 'Lolo Trio', 0.99, 'unit', 'pièce'),
    ('74', 'Maïs Doux Ravier', 0, 'unit', 'ravier'),
    ('75', 'Navet', 0, 'weight', 'kg'),
    ('76', 'Navet Blanc', 1.79, 'weight', 'kg'),
    ('77', 'Navet Noir', 2.99, 'weight', 'kg'),
    ('78', 'Navet Rouge', 2.99, 'weight', 'kg'),
    ('79', 'Oignon Vert Botte', 0, 'unit', 'botte'),
    ('80', 'Olive Fraîche', 4.99, 'weight', 'kg'),
    ('85', 'Petit Pois', 6.99, 'weight', 'kg'),
    ('87', 'Piment Rouge', 3.99, 'weight', 'kg'),
    ('88', 'Piment Vert', 0, 'unit', 'pièce'),
    ('89', 'Piment Vert Fort', 0, 'unit', 'sachet'),
    ('99', 'Pissenlits', 0, 'unit', 'botte'),
    ('100', 'Poireaux Botte', 0, 'unit', 'botte'),
    ('101', 'Poireaux Vrac', 1.49, 'weight', 'kg'),
    ('103', 'Poivron Jaune', 2.99, 'weight', 'kg'),
    ('104', 'Poivron Long Rouge', 1.79, 'unit', 'paquet'),
    ('105', 'Poivron Long Blanc', 1.79, 'unit', 'paquet'),
    ('106', 'Poivron Long Jaune', 0.99, 'weight', 'kg'),
    ('107', 'Poivron Long Rouge Kg', 1.99, 'weight', 'kg'),
    ('108', 'Poivron Long Vert', 0.99, 'weight', 'kg'),
    ('109', 'Poivron Rouge', 0, 'weight', 'kg'),
    ('110', 'Poivron Turc Vrac', 0, 'weight', 'kg'),
    ('111', 'Poivron Turc 400g', 1.00, 'unit', 'paquet'),
    ('112', 'Poivron Vert', 0, 'weight', 'kg'),
    ('113', 'Potiron', 0.59, 'weight', 'kg'),
    ('114', 'Potiron Butternut', 1.19, 'weight', 'kg'),
    ('115', 'Potiron Bleu', 0, 'weight', 'kg'),
    ('116', 'Radicchio', 3.99, 'weight', 'kg'),
    ('117', 'Radis Rouge', 1.29, 'unit', 'botte'),
    ('118', 'Ramonas Blanc', 1.49, 'unit', 'pièce'),
    ('119', 'Ramonas Noir', 1.49, 'unit', 'pièce'),
    ('120', 'Rape Italie', 3.99, 'weight', 'kg'),
    ('121', 'Rhubarbe Bottes', 0, 'unit', 'botte'),
    ('122', 'Salade Batavia', 0.69, 'unit', 'pièce'),
    ('123', 'Salade Iceberg', 0.99, 'unit', 'pièce'),
    ('124', 'Salade Laitue', 0, 'unit', 'pièce'),
    ('125', 'Salade Romaine', 0.99, 'unit', 'pièce'),
    ('126', 'Salade Rouge', 0, 'unit', 'pièce'),
    ('127', 'Scarole', 1.99, 'unit', 'pièce'),
    ('128', 'Cagla Amande 250g', 3.99, 'unit', 'ravier'),
    ('130', 'Tomate', 0.99, 'weight', 'kg'),
    ('131', 'Tomate Cœur Bœuf', 0, 'weight', 'kg'),
    ('132', 'Tomate Cerise 250g', 0, 'unit', 'barquette'),
    ('133', 'Tomate Cherrystar', 0, 'weight', 'kg'),
    ('134', 'Tomate Grappe', 3.99, 'weight', 'kg'),
    ('135', 'Tomate Mini San', 0, 'weight', 'kg'),
    ('136', 'Tomate Ministar', 0, 'weight', 'kg'),
    ('137', 'Tomate Ruby Red', 0, 'weight', 'kg'),
    ('138', 'Tomate San Marzano', 0, 'weight', 'kg'),
    ('139', 'Tomate Shaker', 0, 'unit', 'barquette'),
    ('140', 'Topinambour', 1.00, 'weight', 'kg'),
    ('141', 'Haricot Blanc Géant', 0, 'weight', 'kg'),
    ('142', 'Choux Fleur Mauve', 1.79, 'unit', 'pièce'),
    ('145', 'Champignons 250g', 1.49, 'unit', 'barquette'),
    ('150', 'Ail 3 Têtes', 2.29, 'unit', 'sachet'),
    ('151', 'Ail Sec Blanche', 4.95, 'weight', 'kg'),
    ('152', 'Ail Tresse 500g', 0, 'unit', 'tresse'),
    ('153', 'Ail Tresse Fumé', 0, 'unit', 'tresse'),
    ('154', 'Ail Tresse Violet', 0, 'unit', 'tresse'),
    ('155', 'Ail Violet Vrac', 11.95, 'weight', 'kg'),
    ('156', 'Échalotte Cuisse', 0, 'weight', 'kg'),
    ('157', 'Échalottes Filet', 0, 'unit', 'filet'),
    ('158', 'Oignon 5kg', 2.99, 'unit', 'filet'),
    ('159', 'Oignon Blanc', 2.29, 'weight', 'kg'),
    ('160', 'Oignon Classic Vrac', 0, 'weight', 'kg'),
    ('161', 'Oignon Doux Gros', 1.99, 'weight', 'kg'),
    ('162', 'Oignon Filet 1kg', 0, 'unit', 'filet'),
    ('163', 'Oignon Rouge', 0, 'weight', 'kg'),
    ('164', 'Oignon Rouge Filet', 1.99, 'unit', 'filet'),
    ('170', 'PDT Ordinaire 5kg', 1.99, 'unit', 'sachet'),
    ('171', 'PDT Douce Rouge', 0.93, 'weight', 'kg'),
    ('172', 'PDT Franceline 2.5kg', 2.99, 'unit', 'sachet'),
    ('173', 'PDT Frites 10kg', 4.00, 'unit', 'sachet'),
    ('174', 'PDT Agathe', 0.99, 'weight', 'kg'),
    ('175', 'PDT Charlottes 2.5kg', 2.99, 'unit', 'sachet'),
    ('176', 'PDT Frites 5kg', 1.99, 'unit', 'sachet'),
    ('177', 'PDT Nicola 2.5kg', 2.99, 'unit', 'sachet'),
    ('178', 'PDT Ordinaire 10kg', 4.99, 'unit', 'sachet'),
    ('179', 'PDT Rouge Vrac', 0, 'weight', 'kg'),
    ('180', 'PDT Rouge 10kg', 6.99, 'unit', 'sachet'),
    ('181', 'PDT Rouge 5kg', 1.99, 'unit', 'sachet'),
    ('182', 'PDT Spunta Nouvelle', 1.19, 'weight', 'kg'),
    ('183', 'Cresson Fort Botte', 1.89, 'unit', 'botte'),
    ('184', 'Aneth Botte', 0, 'unit', 'botte'),
    ('185', 'Coriandre Espagne', 0.99, 'unit', 'botte'),
    ('186', 'Coriandre Maroc', 0.39, 'unit', 'botte'),
    ('187', 'Chiba Herbes Maroc', 0, 'unit', 'botte'),
    ('188', 'Cresson Doux', 0, 'unit', 'botte'),
    ('189', 'Menthe Espagne', 0, 'unit', 'botte'),
    ('190', 'Menthe Maroc', 0.39, 'unit', 'botte'),
    ('191', 'Panais', 2.99, 'weight', 'kg'),
    ('192', 'Persil Frisé', 0.39, 'unit', 'botte'),
    ('193', 'Persil Plat', 1.39, 'unit', 'botte'),
    ('194', 'Roquettes 125g', 1.89, 'unit', 'barquette'),
    ('195', 'Basilic Pot', 2.29, 'unit', 'pot'),
    ('196', 'Thym Pot', 2.29, 'unit', 'pot'),
    ('200', 'Sucrine 8pcs', 0, 'unit', 'sachet'),
    ('201', 'Aubergine Graffiti', 3.99, 'weight', 'kg'),
    ('203', 'Maïs Doux Feuille', 0, 'unit', 'pièce'),
    ('204', 'Mini Piments', 0, 'unit', 'ravier'),
    ('210', 'Easy Blé 150g', 0, 'unit', 'sachet'),
    ('211', 'Easy Carottes Râpées', 0, 'unit', 'sachet'),
    ('212', 'Easy Choux Blanc', 0, 'unit', 'sachet'),
    ('213', 'Easy Choux Rouge', 0, 'unit', 'sachet'),
    ('214', 'Easy Cœur Laitue', 0, 'unit', 'sachet'),
    ('215', 'Easy Frisée 150g', 0, 'unit', 'sachet'),
    ('216', 'Easy Roquettes 80g', 0, 'unit', 'sachet'),
    ('217', 'Easy Jeunes Pousses', 0, 'unit', 'sachet'),
    ('218', 'Easy Julienne Soupe', 0, 'unit', 'sachet'),
    ('219', 'Easy Salade Iceberg', 0, 'unit', 'sachet'),
    ('220', 'Easy Salade Mixte', 0.99, 'unit', 'sachet'),
    ('232', 'Carotte Violettes', 1.99, 'weight', 'kg'),
    ('235', 'Manioc', 0, 'weight', 'kg'),
    ('254', 'Aubergine Blanche', 0, 'weight', 'kg'),
    ('5', 'Choux Turc Pièce', 0.24, 'unit', 'pièce'),
    ('6', 'Haricot Coco', 3.99, 'weight', 'kg')
  ) AS v(barcode, name, price, type, unit)
  WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.barcode = v.barcode);

END $$;