// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://htoihjbbwzpnyphcfomq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0b2loamJid3pwbnlwaGNmb21xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkyNjgwNTIsImV4cCI6MjA3NDg0NDA1Mn0.a4QW1dpXl7_48YHEQ8_pP8lTB8rLAU7u1YCdcP3jkJg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});